# Generated by Django 6.0 on 2026-01-02 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('vin_number', models.CharField(blank=True, max_length=17)),
                ('license_plate_number', models.CharField(blank=True, max_length=15)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('purchased_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchased_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('dealer_name', models.CharField(blank=True, max_length=100)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sold_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='gasoline', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'make', 'model'],
            },
        ),
    ]
