# Generated by Django 6.0 on 2026-01-03 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gallons', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('mpg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kwh_per_mile', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cost_per_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('cost_per_gallon_reference', models.DecimalField(blank=True, decimal_places=2, help_text='Reference gas price for MPGe calculation', max_digits=5, null=True)),
                ('mpge', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='autolog.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Fuel entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
