# Generated by Django 6.0 on 2026-01-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0002_fuelentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelentry',
            name='kwh_per_mile',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
