# Generated by Django 6.0 on 2026-01-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0003_alter_fuelentry_kwh_per_mile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('oil', 'Oil Change'), ('repairs', 'Repairs'), ('tires', 'Tires'), ('wash', 'Wash'), ('accessories', 'Accessories')], max_length=20)),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_entries', to='autolog.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Maintenance entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
