# Generated by Django 6.0 on 2026-01-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0004_maintenanceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('insurance', 'Insurance'), ('registration', 'Registration')], max_length=20)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_expenses', to='autolog.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Other expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
