# Generated by Django 6.0 on 2026-01-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0005_otherexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpense',
            name='expense_type',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('registration', 'Registration'), ('loan', 'Loan Payment')], max_length=20),
        ),
    ]
