# Generated by Django 6.0 on 2026-01-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0006_alter_otherexpense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loan_auto_payment',
            field=models.BooleanField(default=False, help_text='Automatically generate monthly payment entries'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loan_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Annual interest rate as percentage (e.g., 5.75 for 5.75%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loan_payment_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of month payment is due (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loan_term_months',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of months for the loan', null=True),
        ),
    ]
