# Generated by Django 6.0 on 2026-01-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0007_vehicle_loan_amount_vehicle_loan_auto_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated value (for unsold vehicles)', max_digits=10, null=True),
        ),
    ]
