# Generated by Django 6.0 on 2026-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0008_add_vehicle_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_value_date',
            field=models.DateField(blank=True, help_text='Date of current value estimate', null=True),
        ),
    ]
