# Generated by Django 6.0 on 2026-01-07 18:16

import autolog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0010_add_vehicle_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to=autolog.models.vehicle_image_upload_path),
        ),
    ]
