# Generated by Django 6.0 on 2026-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0011_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Down payment amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='financing_type',
            field=models.CharField(choices=[('none', 'None'), ('loan', 'Loan'), ('lease', 'Lease')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lease_auto_payment',
            field=models.BooleanField(default=False, help_text='Automatically generate monthly payment entries'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lease_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly lease payment amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lease_payment_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of month payment is due (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lease_term_months',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of months for the lease', null=True),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='expense_type',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('registration', 'Registration'), ('loan', 'Loan Payment'), ('lease', 'Lease Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount financed (after down payment)', max_digits=10, null=True),
        ),
    ]
