# Generated by Django 6.0 on 2026-01-08 14:25

from django.db import migrations


def convert_payment_types(apps, schema_editor):
    """Convert 'loan' and 'lease' expense types to 'vehicle_payment'"""
    OtherExpense = apps.get_model('autolog', 'OtherExpense')

    # Convert loan payments
    loan_payments = OtherExpense.objects.filter(expense_type='loan')
    for payment in loan_payments:
        payment.expense_type = 'vehicle_payment'
        # Ensure notes indicate it's a loan payment
        if 'loan' not in payment.notes.lower():
            payment.notes = f'Loan payment - {payment.notes}' if payment.notes else 'Loan payment'
        payment.save()

    # Convert lease payments
    lease_payments = OtherExpense.objects.filter(expense_type='lease')
    for payment in lease_payments:
        payment.expense_type = 'vehicle_payment'
        # Ensure notes indicate it's a lease payment
        if 'lease' not in payment.notes.lower():
            payment.notes = f'Lease payment - {payment.notes}' if payment.notes else 'Lease payment'
        payment.save()


def reverse_conversion(apps, schema_editor):
    """Reverse the conversion if needed"""
    OtherExpense = apps.get_model('autolog', 'OtherExpense')

    # Convert back based on notes
    vehicle_payments = OtherExpense.objects.filter(expense_type='vehicle_payment')
    for payment in vehicle_payments:
        if 'loan' in payment.notes.lower():
            payment.expense_type = 'loan'
            payment.save()
        elif 'lease' in payment.notes.lower():
            payment.expense_type = 'lease'
            payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0012_vehicle_down_payment_vehicle_financing_type_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_payment_types, reverse_conversion),
    ]
