# Generated by Django 6.0 on 2026-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolog', '0013_convert_payment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='loan_monthly_payment_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override calculated monthly payment (leave blank to use calculated amount)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='expense_type',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('registration', 'Registration'), ('vehicle_payment', 'Vehicle Payment')], max_length=20),
        ),
    ]
